### ISSUE TITLE
使用lsposed注入目标，路线模拟基站遥感等仍提示启用专业版，无法使用

### ISSUE THREAD

**Issue by 5120zyc** [kazutoiris/infinite-illusion#1]
使用lsposed注入目标，路线模拟基站遥感等仍提示启用专业版，无法使用
已关闭动态注入

**Comment by 5120zyc** [comment]
再次测试，路线模拟不提示专业版但功能失效（只留在起点）。不确定是否只是UI 解锁

**Comment by 5120zyc** [comment]
1.3.5Beta1592

**Comment by kazutoiris** [comment]
Do you **truly** understand what this module is designed to do? It's not intended to unlock the VIP, but rather to bypass some restrictions.
